language: node_js

node_js:
  - 'lts/*'

cache: npm

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - npm run lint
  - npm run cover

after_success:
  - npx codecov -f coverage/lcov.info
